[tool.isort]
profile = 'black'
skip = ['env', 'migrations']

[tool.black]
line-length = 180
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
  | \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | \env
  | migrations
)/
'''

[tool.poetry]
name = "simple-locations"
version = "2.78"
description = "The common location package for Catalpa's projects"
authors = ["Joshua Brooks <josh.vdbroek@gmail.com>"]
license = "BSD"

[tool.poetry.dependencies]
python = "^3.7"
django-mptt = "^0.13.4"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
flake8 = "^4.0.1"
isort = "^5.9.3"
pre-commit = "^2.15.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
