# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-29 05:00
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='area',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='catchment_areas',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='location',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='facility',
            name='type',
        ),
        migrations.AddField(
            model_name='area',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
        migrations.DeleteModel(
            name='FacilityType',
        ),
    ]
