# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-09 06:13
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('simple_locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='area',
            managers=[
                ('tree', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
