# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-30 02:27
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('simple_locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='area',
            managers=[
                ('tree', django.db.models.manager.Manager()),
            ],
        ),
    ]
