# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-30 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_locations', '0002_auto_20170130_1127'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='area',
            managers=[
            ],
        ),
    ]
