# Generated by Django 4.2.4 on 2023-08-07 03:47

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import simple_locations.models


class Migration(migrations.Migration):
    dependencies = [
        ("simple_locations", "0013_auto_20220307_0618"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="validity_period",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                default=simple_locations.models.default_date_range
            ),
        ),
    ]
