# Generated by Django 4.2.4 on 2023-10-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simple_locations", "0014_area_validity_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="metadata",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
