# Generated by Django 5.2.3 on 2025-08-14 02:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.contrib.gis.geos import Point


def copy_point_to_location(apps, schema_editor):
    Area = apps.get_model("simple_locations", "Area")
    PointModel = apps.get_model("simple_locations", "Point")
    for area in Area.objects.all():
        if hasattr(area, "location_id") and area.location_id:
            try:
                point = PointModel.objects.get(pk=area.location_id)
                if point.latitude is not None and point.longitude is not None:
                    area.location_point = Point(float(point.longitude), float(point.latitude), srid=4326)
                    area.save(update_fields=["location_point"])
            except PointModel.DoesNotExist:
                pass


class Migration(migrations.Migration):
    dependencies = [
        ("simple_locations", "0015_add_area_metadata"),
    ]

    operations = [
        # 1. Add a new PointField
        migrations.AddField(
            model_name="area",
            name="location_point",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        # 2. Copy data from old FK to new PointField
        migrations.RunPython(copy_point_to_location, reverse_code=migrations.RunPython.noop),
        # 3. Remove the old ForeignKey field
        migrations.RemoveField(
            model_name="area",
            name="location",
        ),
        # 4. Rename the new PointField to 'location'
        migrations.RenameField(
            model_name="area",
            old_name="location_point",
            new_name="location",
        ),
    ]
