name: Python

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

    steps:
    - uses: actions/checkout@v3
    - name: Install python and poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        cache: "poetry"
    - run: poetry install --with dev --no-root

    - name: Lint with flake8
      if: always()
      run: |
        poetry run flake8 .

    - name: Install OS level dependencies
      run: |
          sudo apt-get update
          sudo apt-get install binutils libproj-dev gdal-bin

    - name: Test with pytest (no PostGIS)
      if: always()
      run: poetry run pytest -m "not postgis"

    - name: Test with pytest (PostGIS)
      if: always()
      run: poetry run pytest -m postgis

    - name: Test mypy
      if: always()
      run: poetry run mypy .

    - name: Test with black
      if: always()
      run: poetry run black --check .

    # Service containers to run postgres
    services:
        # Label used to access the service container
        postgres:
            # Docker Hub image
            image: postgis/postgis:15-3.3
            env:
                POSTGRES_PASSWORD: postgres
            options: >-
                --health-cmd pg_isready
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
            ports:
                - 5432:5432
