name: Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install python and poetry
      run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: "3.8"
        cache: "poetry"
    - run: poetry install --with dev

    - name: Lint with flake8
      if: always()
      run: |
        poetry run flake8 .

    - name: Test with pytest
      if: always()
      run: poetry run pytest

    - name: Test mypy
      if: always()
      run: poetry run mypy .

    - name: Test with black
      if: always()
      run: poetry run black --check .
